services:
  - docker
before_script:
  - |
    docker run -it -d \
      -v /var/run/docker.sock:/var/run/docker.sock \
      -e DOCKER_USERNAME=${DOCKER_USERNAME} \
      -e DOCKER_PASSWORD=${DOCKER_PASSWORD} \
      -e GITHUB_URL=${GITHUB_URL} \
      --name docker-test \
      piotrmurbanski/docker-test:latest
script:
  - docker exec docker-test /stages/01_clone.sh
  - docker exec docker-test /stages/02_build.sh
  - docker exec docker-test /stages/03_test.sh
  - docker exec docker-test /stages/04_archive.sh
